@user=jens
@password=password

###############
### GraphQL ###
###############

### Get Products
POST http://{{user}}:{{password}}@localhost:4984/retail/_graphql HTTP/1.1
X-Request-Type: GraphQL

query {
    products(search: "Hat", offset: 0, limit: 5) {
        id,
        name,
        image,
        price
    }
}

### Get Cart
POST http://{{user}}:{{password}}@localhost:4984/retail/_graphql HTTP/1.1
X-Request-Type: GraphQL

query {
    cart {
        items {
            product {
                id,
                name,
                image,
                price
            },
            count
        },
        count
    }
}

### Add to Cart
POST http://{{user}}:{{password}}@localhost:4984/retail/_graphql HTTP/1.1
X-Request-Type: GraphQL

mutation {
    addToCart(productId: "product1")
}

### Order Cart
POST http://{{user}}:{{password}}@localhost:4984/retail/_graphql HTTP/1.1
X-Request-Type: GraphQL

mutation {
    orderCart(storeId: "store1") {
        id,
        store {
            id,
            name,
            email
        },
        items {
            product {
                id,
                name,
                image,
                price
            },
            count
        }
    }
}

### Get Store
POST http://{{user}}:{{password}}@localhost:4984/retail/_graphql HTTP/1.1
X-Request-Type: GraphQL

query {
    store(id: "store1") {
        id,
        name,
        email
    }
}

### Get Order
POST http://{{user}}:{{password}}@localhost:4984/retail/_graphql HTTP/1.1
X-Request-Type: GraphQL

query {
    order(id: "2ff51aeaf464a2d1cade5ae5b6d882d5") {
        id,
        status,
        store {
            id,
            name,
            email
        },
        items {
            product {
                id,
                name,
                image,
                price
            },
            count
        }
    }
}

### Get Orders
POST http://{{user}}:{{password}}@localhost:4984/retail/_graphql HTTP/1.1
X-Request-Type: GraphQL

query {
    orders(storeId: "store2") {
        id,
        status,
        store {
            id,
            name,
            email
        },
        items {
            product {
                id,
                name,
                image,
                price
            },
            count
        }
    }
}

### Set Order Status PROCESSING PREPARING_FOR_PICKUP PICKED_UP
POST http://{{user}}:{{password}}@localhost:4984/retail/_graphql HTTP/1.1
X-Request-Type: GraphQL

mutation {
    setOrderStatus(orderId: "2ff51aeaf464a2d1cade5ae5b6d882d5", status: PREPARING_FOR_PICKUP)
}

### Get Inventory
POST http://{{user}}:{{password}}@localhost:4984/retail/_graphql HTTP/1.1
X-Request-Type: GraphQL

query {
    inventory(storeId: "store1") {
        product {
            id
            name
        },
        quantity
    }
}

############
### REST ###
############

### Get Products
POST http://{{user}}:{{password}}@localhost:4984/retail/_function/products HTTP/1.1
Content-Type: application/json

{
    "search": null,
    "offset": 0,
    "limit": 5
}