@user=admin
@password=password

###############
### GraphQL ###
###############

### Get Cart
POST http://{{user}}:{{password}}@localhost:4984/retail/_graphql HTTP/1.1
X-Request-Type: GraphQL

query {
    cart {
        items {
            product {
                id,
                name,
                image,
                price
            },
            count
        },
        count
    }
}

# query {
#     cart {
#         items {
#             id,
#             name,
#             image,
#             price
#         }
#     }
# }

### Add to Cart
POST http://{{user}}:{{password}}@localhost:4984/retail/_graphql HTTP/1.1
X-Request-Type: GraphQL

mutation {
    addToCart(productId: "product2")
}

############
### REST ###
############

### Get Cart
GET http://{{user}}:{{password}}@localhost:4984/retail/cart:admin HTTP/1.1